#!/bin/sh
#
# This script does not have a stable API.
#
# It locates a local gitstatusd binary. It never downloads or builds one:
# if no binary is found, build it with `./build -w -s -d docker`.

_gitstatus_install_daemon_found() {
  local installed="$1"
  shift
  [ $# = 0 ] || "$@" "$daemon" "$version" "$installed"
}

_gitstatus_install_main() {
  if [ -n "${ZSH_VERSION:-}" ]; then
    emulate -L sh -o no_unset
  else
    set -u
  fi

  local argv1="$1"
  shift

  local gitstatus_dir= e=
  local opt= OPTARG= OPTIND=1

  while getopts ':d:e:h' opt "$@"; do
    case "$opt" in
      h)
        command cat <<\END
Usage: install [-d DIR] [-e ERRFD] [-- CMD [ARG]...]

If positional arguments are specified, call this on success:

  CMD [ARG]... DAEMON VERSION INSTALLED

DAEMON is path to gitstatusd. VERSION is a glob pattern for the
version this daemon should support; it's supposed to be passed as
-G to gitstatusd. INSTALLED is always 0: this script never downloads
or builds gitstatusd, it only locates an existing binary. If none is
found, it fails and tells the user to build one with `./build`.

Options:

  -d DIR     use this instead of `dirname "$0"`
  -e ERRFD   write error messages to this file descriptor
END
        return
      ;;
      d)
        if [ -n "$gitstatus_dir" ]; then
          >&2 echo "[gitstatus] error: duplicate option: -$opt"
          return 1
        fi
        if [ -z "$OPTARG" ]; then
          >&2 echo "[error] incorrect value of -$opt: $OPTARG"
          return 1
        fi
        gitstatus_dir="$OPTARG"
      ;;
      e)
        if [ -n "$e" ]; then
          >&2 echo "[gitstatus] error: duplicate option: -$opt"
          return 1
        fi
        if [ -z "$OPTARG" ]; then
          >&2 echo "[error] incorrect value of -$opt: $OPTARG"
          return 1
        fi
        e="$OPTARG"
      ;;
      \?) >&2 echo "[gitstatus] error: invalid option: -$OPTARG"           ; return 1;;
      :)  >&2 echo "[gitstatus] error: missing required argument: -$OPTARG"; return 1;;
      *)  >&2 echo "[gitstatus] internal error: unhandled option: -$opt"   ; return 1;;
    esac
  done

  shift "$((OPTIND - 1))"

  : "${e:=2}"
  : "${gitstatus_dir:=$argv1}"

  local daemon="${GITSTATUS_DAEMON:-}"

  if [ -n "${daemon##/*}" ]; then
    >&2 echo "[gitstatus] error: GITSTATUS_DAEMON is not absolute path: $daemon"
    return 1
  fi
  if [ -z "$daemon" -a -e "$gitstatus_dir"/usrbin/gitstatusd ]; then
    daemon="$gitstatus_dir"/usrbin/gitstatusd
  fi
  if [ -n "$daemon" ]; then
    local gitstatus_version= libgit2_version=
    if ! . "$gitstatus_dir"/build.info; then
      >&2 echo "[gitstatus] internal error: failed to source build.info"
      return 1
    fi
    if [ -z "$gitstatus_version" ]; then
      >&2 echo "[gitstatus] internal error: empty gitstatus_version in build.info"
      return 1
    fi
    local version="$gitstatus_version"
    _gitstatus_install_daemon_found 0 "$@"
    return
  fi

  >&"$e" printf 'No \033[32mgitstatusd\033[0m binary found.\n'
  >&"$e" printf '\n'
  >&"$e" printf 'Build it from source, then restart your shell:\n'
  >&"$e" printf '\n'
  >&"$e" printf '  \033[1mcd %s && ./build -w -s -d docker\033[0m\n' "$gitstatus_dir"
  >&"$e" printf '\n'
  return 1
}

if [ -z "${0##*/*}" ]; then
  _gitstatus_install_main "${0%/*}" "$@"
else
  _gitstatus_install_main . "$@"
fi
